DOT_ABSTRA_DIR = ".abstra"

LOCAL_LOGS_DIR_PATH = f"{DOT_ABSTRA_DIR}/logs"
TASKS_DIR_PATH = f"{DOT_ABSTRA_DIR}/tasks"
EXECUTIONS_DIR_PATH = f"{DOT_ABSTRA_DIR}/executions"
PERSISTENT_DIR_PATH = f"{DOT_ABSTRA_DIR}/persistent"
CACHED_VERSIONS_DIR_PATH = f"{DOT_ABSTRA_DIR}/cached_versions"
CONFIG_BACKUP_DIR_PATH = f"{DOT_ABSTRA_DIR}/config_file_backups"

CREDENTIALS_FILEPATH = f"{DOT_ABSTRA_DIR}/credentials"
TEST_DATA_FILEPATH = f"{DOT_ABSTRA_DIR}/test_data.json"

GIT_DIR_PATH = ".git"
GITIGNORE_FILEPATH = ".gitignore"
ABSTRA_TABLES_FILEPATH = "abstra-tables.json"
