name: Code check

on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code_check:
    runs-on: ubuntu-latest
    env:
      ENV: test

    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pytest black

      - name: Lint
        run: |
          black --check ./abstra

      - name: Run Unit Tests
        run: pytest
